apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cnoe-imp
  region: us-east-1
  version: "1.28"
managedNodeGroups:
  - name: managed-ng-1
    instanceType: t2.medium
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 30
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      role: general-purpose
iam:
  withOIDC: true
addons:
- name: aws-ebs-csi-driver
  version: "v1.20.0-eksbuild.1"
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
# iamIdentityMappings:
#   - arn: arn:aws:iam::000000000000:role/Admin
#     groups:
#       - system:masters
#     username: admin
#     noDuplicateARNs: true # prevents shadowing of ARNs